name: "go-pallet"

on:
  workflow_dispatch:
  push:
  schedule:
    # Runs at 16:30 UTC on day-of-month 2 (Every day-of-month 2 at AM 01:30 JST, my time)
    # See: https://crontab.guru/
    - cron: '30 16 2 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on container
        run: docker-compose run go-pallet
